/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "h1"
        | "h2"
        | "h3"
        | "h4"
        | "h5"
        | "h6"
        | "blockquote"
        | "center";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | ({
            _key: string;
          } & TextColor)
        | {
            href?: string;
            _type: "link";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type Seo = {
  _type: "seo";
  seoTitle: string;
  seoDescription: string;
  seoImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoKeywords: Array<string>;
};

export type Link = {
  _type: "link";
  label: string;
  url: string;
  openInNewTab?: boolean;
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  name: string;
  slug: Slug;
  description: BlockContent;
  content: BlockContent;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type PrivacyPolicies = {
  _id: string;
  _type: "privacyPolicies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  policyTitle: BlockContent;
  policyContent: BlockContent;
};

export type Terms = {
  _id: string;
  _type: "terms";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  termsTitle: BlockContent;
  termsContent: BlockContent;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerHeading: string;
  herobannerTitle: BlockContent;
  herobannerDescription: BlockContent;
  herobannerBgImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  herobannerMobileBgImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  herobannerButtonList: Array<
    {
      _key: string;
    } & Link
  >;
  herobannerTags: Array<string>;
  formTitle: BlockContent;
  formButtonLable: string;
  noteIcon: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  note: BlockContent;
  contactDetailTitle: BlockContent;
  contactDetailItems: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title: string;
    link: Link;
    _key: string;
  }>;
  statsList: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    value: string;
    valuePostfix?: string;
    name: string;
    _key: string;
  }>;
  faqsHeading: string;
  faqsTitle: BlockContent;
  faqs: Array<{
    question: string;
    answer: BlockContent;
    _key: string;
  }>;
  preFooterBgImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  preFooterTitle: BlockContent;
  preFooterDescription: BlockContent;
  preFooterButton: Link;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogoDark: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headerLogoLight: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headerLinks: Array<
    {
      _key: string;
    } & Link
  >;
  headerButton: Link;
  footerLogo: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  footerContent: BlockContent;
  footerSocialLinks: Array<{
    logo: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    platformName: string;
    url: string;
    _key: string;
  }>;
  footerQuickLinks: Array<
    {
      _key: string;
    } & Link
  >;
  footerContactLinks: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title: string;
    link: Link;
    _key: string;
  }>;
  footerCopyrightText: BlockContent;
  footerLegalLinks: Array<
    {
      _key: string;
    } & Link
  >;
  statsList: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    value: string;
    valuePostfix?: string;
    name: string;
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerLeftImages: Array<{
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  herobannerRightImages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  herobannerHeading: BlockContent;
  herobannerTitle: BlockContent;
  herobannerDescription: BlockContent;
};

export type HighlightColor = {
  _type: "highlightColor";
  label?: string;
  value?: string;
};

export type TextColor = {
  _type: "textColor";
  label?: string;
  value?: string;
};

export type SimplerColor = {
  _type: "simplerColor";
  label?: string;
  value?: string;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Seo
  | Link
  | Tool
  | Slug
  | PrivacyPolicies
  | Terms
  | ContactPage
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | HomePage
  | HighlightColor
  | TextColor
  | SimplerColor
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/query.ts
// Variable: settingQuery
// Query: *[_type == 'settings' && _id == 'settings'][0]{    ...,}
export type SettingQueryResult = {
  _id: "settings";
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogoDark: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headerLogoLight: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  headerLinks: Array<
    {
      _key: string;
    } & Link
  >;
  headerButton: Link;
  footerLogo: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  footerContent: BlockContent;
  footerSocialLinks: Array<{
    logo: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    platformName: string;
    url: string;
    _key: string;
  }>;
  footerQuickLinks: Array<
    {
      _key: string;
    } & Link
  >;
  footerContactLinks: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title: string;
    link: Link;
    _key: string;
  }>;
  footerCopyrightText: BlockContent;
  footerLegalLinks: Array<
    {
      _key: string;
    } & Link
  >;
  statsList: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    value: string;
    valuePostfix?: string;
    name: string;
    _key: string;
  }>;
} | null;

// Source: sanity/lib/query.ts
// Variable: homePageQuery
// Query: *[ _type == "homePage" && _id == 'homePage'][0]{        ...,                seo{            ...,            seoImage{                asset->{                    url,                }            }        },    }
export type HomePageQueryResult = {
  _id: "homePage";
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    seoTitle: string;
    seoDescription: string;
    seoImage: {
      asset: {
        url: string;
      };
    };
    seoKeywords: Array<string>;
  };
  herobannerLeftImages: Array<{
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  herobannerRightImages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  herobannerHeading: BlockContent;
  herobannerTitle: BlockContent;
  herobannerDescription: BlockContent;
} | null;

// Source: sanity/lib/query.ts
// Variable: contactPageQuery
// Query: *[ _type == "contactPage" && _id == 'contactPage'][0]{    ...,    seo{        ...,        seoImage{            ...,            asset->,        }    },    "stats": *[ _type == "settings" && _id == "settings"][0]{        statsList[]{            ...,        }    },}
export type ContactPageQueryResult = {
  _id: "contactPage";
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    seoTitle: string;
    seoDescription: string;
    seoImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    seoKeywords: Array<string>;
  };
  herobannerHeading: string;
  herobannerTitle: BlockContent;
  herobannerDescription: BlockContent;
  herobannerBgImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  herobannerMobileBgImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  herobannerButtonList: Array<
    {
      _key: string;
    } & Link
  >;
  herobannerTags: Array<string>;
  formTitle: BlockContent;
  formButtonLable: string;
  noteIcon: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  note: BlockContent;
  contactDetailTitle: BlockContent;
  contactDetailItems: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title: string;
    link: Link;
    _key: string;
  }>;
  statsList: Array<{
    icon: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    value: string;
    valuePostfix?: string;
    name: string;
    _key: string;
  }>;
  faqsHeading: string;
  faqsTitle: BlockContent;
  faqs: Array<{
    question: string;
    answer: BlockContent;
    _key: string;
  }>;
  preFooterBgImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  preFooterTitle: BlockContent;
  preFooterDescription: BlockContent;
  preFooterButton: Link;
  stats: {
    statsList: Array<{
      icon: {
        asset: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      value: string;
      valuePostfix?: string;
      name: string;
      _key: string;
    }>;
  } | null;
} | null;

// Source: sanity/lib/query.ts
// Variable: privacyPoliciesQuery
// Query: *[_type == "privacyPolicies" && _id == "privacyPolicies"][0]{    ...,    seo{        ...,        seoImage{            ...,            asset->,        }    }}
export type PrivacyPoliciesQueryResult = {
  _id: "privacyPolicies";
  _type: "privacyPolicies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    seoTitle: string;
    seoDescription: string;
    seoImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    seoKeywords: Array<string>;
  };
  policyTitle: BlockContent;
  policyContent: BlockContent;
} | null;

// Source: sanity/lib/query.ts
// Variable: termsQuery
// Query: *[_type == "terms" && _id == "terms"][0]{    ...,    seo{        ...,        seoImage{            ...,            asset->,        }    }}
export type TermsQueryResult = {
  _id: "terms";
  _type: "terms";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    seoTitle: string;
    seoDescription: string;
    seoImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    seoKeywords: Array<string>;
  };
  termsTitle: BlockContent;
  termsContent: BlockContent;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == 'settings' && _id == 'settings'][0]{\n    ...,\n}\n": SettingQueryResult;
    "\n    *[ _type == \"homePage\" && _id == 'homePage'][0]{\n        ...,\n        \n        seo{\n            ...,\n            seoImage{\n                asset->{\n                    url,\n                }\n            }\n        },\n    }\n": HomePageQueryResult;
    '\n*[ _type == "contactPage" && _id == \'contactPage\'][0]{\n    ...,\n    seo{\n        ...,\n        seoImage{\n            ...,\n            asset->,\n        }\n    },\n    "stats": *[ _type == "settings" && _id == "settings"][0]{\n        statsList[]{\n            ...,\n        }\n    },\n}\n': ContactPageQueryResult;
    '\n*[_type == "privacyPolicies" && _id == "privacyPolicies"][0]{\n    ...,\n    seo{\n        ...,\n        seoImage{\n            ...,\n            asset->,\n        }\n    }\n}\n': PrivacyPoliciesQueryResult;
    '\n*[_type == "terms" && _id == "terms"][0]{\n    ...,\n    seo{\n        ...,\n        seoImage{\n            ...,\n            asset->,\n        }\n    }\n}\n': TermsQueryResult;
  }
}
