import {
  PDFDocument,
  PDFFont,
  StandardFonts,
} from "pdf-lib";

import {
  getPageSize,
  PageSize,
  prepareContentLines,
} from "../utils/pdfUtils";

export type PdfGenerationMode = "byPage" | "byContent";

export type PdfOrientation = "portrait" | "landscape";

export interface GeneratePdfOptions {
  mode: PdfGenerationMode;

  fileName?: string;

  pageCount?: number;

  content?: string;

  orientation?: PdfOrientation;
  fontSize?: number;
  lineHeight?: number;
  margin?: number;

  showPageNumbers?: boolean;
}

export interface GeneratedPdf {
  blob: Blob;
  filename: string;
  size: number;
  mimeType: string;
}

function drawPageNumber(
  page: ReturnType<PDFDocument["addPage"]>,
  pageNumber: number,
  pageSize: PageSize,
  font: PDFFont,
  fontSize: number,
  margin: number
) {
  const text = `Page ${pageNumber}`;

  const textWidth = font.widthOfTextAtSize(
    text,
    fontSize
  );

  page.drawText(text, {
    x: pageSize.width - margin - textWidth,
    y: 20,
    size: fontSize,
    font,
  });
}

async function generateByPage(
  pageCount: number,
  pageSize: PageSize,
  font: PDFFont,
  fontSize: number,
  margin: number,
  showPageNumbers: boolean,
  pdfDoc: PDFDocument
) {
  if (!Number.isInteger(pageCount) || pageCount <= 0) {
    throw new Error(
      "Page count must be a positive integer."
    );
  }

  for (let i = 0; i < pageCount; i++) {
    const page = pdfDoc.addPage([
      pageSize.width,
      pageSize.height,
    ]);

    page.drawText("Dummy PDF", {
      x: margin,
      y: pageSize.height - margin,
      size: 24,
      font,
    });

    page.drawText(
      "This is a static PDF generated using pdf-lib.",
      {
        x: margin,
        y: pageSize.height - margin - 40,
        size: fontSize,
        font,
      }
    );

    page.drawText(
      "This content is generated by the application.",
      {
        x: margin,
        y: pageSize.height - margin - 70,
        size: fontSize,
        font,
      }
    );

    if (showPageNumbers) {
      drawPageNumber(
        page,
        i + 1,
        pageSize,
        font,
        10,
        margin
      );
    }
  }

  return pageCount;
}

async function generateByContent(
  content: string,
  pageSize: PageSize,
  font: PDFFont,
  fontSize: number,
  lineHeight: number,
  margin: number,
  showPageNumbers: boolean,
  pdfDoc: PDFDocument
) {
  if (!content.trim()) {
    throw new Error("Content cannot be empty.");
  }

  const contentWidth =
    pageSize.width - margin * 2;

  const lines = prepareContentLines(
    content,
    font,
    fontSize,
    contentWidth
  );

  let page = pdfDoc.addPage([
    pageSize.width,
    pageSize.height,
  ]);

  let y = pageSize.height - margin;

  let pageNumber = 1;

  for (const line of lines) {
    if (y - lineHeight < margin) {
      if (showPageNumbers) {
        drawPageNumber(
          page,
          pageNumber,
          pageSize,
          font,
          10,
          margin
        );
      }

      page = pdfDoc.addPage([
        pageSize.width,
        pageSize.height,
      ]);

      pageNumber++;

      y = pageSize.height - margin;
    }

    if (line === "") {
      y -= lineHeight;
      continue;
    }

    page.drawText(line, {
      x: margin,
      y,
      size: fontSize,
      font,
    });

    y -= lineHeight;
  }

  if (showPageNumbers) {
    drawPageNumber(
      page,
      pageNumber,
      pageSize,
      font,
      10,
      margin
    );
  }

  return pageNumber;
}

export async function generatePdf(
  options: GeneratePdfOptions
): Promise<GeneratedPdf> {
  const {
    mode,
    fileName = "sample.pdf",
    pageCount,
    content,
    orientation = "portrait",
    fontSize = 14,
    lineHeight = 20,
    margin = 50,
    showPageNumbers = true,
  } = options;

  if (fontSize <= 0) {
    throw new Error(
      "Font size must be greater than 0."
    );
  }

  if (lineHeight <= 0) {
    throw new Error(
      "Line height must be greater than 0."
    );
  }

  if (margin < 0) {
    throw new Error(
      "Margin cannot be negative."
    );
  }

  const pageSize =
    getPageSize(orientation);

  const pdfDoc =
    await PDFDocument.create();

  const font =
    await pdfDoc.embedFont(
      StandardFonts.Helvetica
    );

  let totalPages: number;

  if (mode === "byPage") {
    if (
      pageCount === undefined
    ) {
      throw new Error(
        "Page count is required for byPage mode."
      );
    }

    totalPages =
      await generateByPage(
        pageCount,
        pageSize,
        font,
        fontSize,
        margin,
        showPageNumbers,
        pdfDoc
      );
  } else if (mode === "byContent") {
    if (
      content === undefined ||
      !content.trim()
    ) {
      throw new Error(
        "Content is required for byContent mode."
      );
    }

    totalPages =
      await generateByContent(
        content,
        pageSize,
        font,
        fontSize,
        lineHeight,
        margin,
        showPageNumbers,
        pdfDoc
      );
  } else {
    throw new Error(
      `Unsupported PDF generation mode: ${mode}`
    );
  }

  const pdfBytes =
    await pdfDoc.save();

  const finalFileName =
    fileName.toLowerCase().endsWith(".pdf")
      ? fileName
      : `${fileName}.pdf`;
      const arrayBuffer = new ArrayBuffer(pdfBytes.byteLength);

      new Uint8Array(arrayBuffer).set(pdfBytes);
      
      const blob = new Blob([arrayBuffer], {
        type: "application/pdf",
      });

  return {
    filename: finalFileName,
    blob,
    mimeType: "application/pdf",
    size: blob.size,
  };
}