"use client";

import { useState } from "react";

import type { GeneratedFile } from "@/types/tools";

import DownloadButton from "@/components/common/download-button";
import PdfGeneratorForm from "./pdf-generator-form";
import PdfPreview from "@/components/common/pdfViewer";

const DEFAULT_CONTENT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit.

This is a sample PDF generated by Developer Utilities.

You can replace this content with your own text and generate a PDF file instantly.`;

export function PdfGenerator() {
  const [content, setContent] =
    useState(DEFAULT_CONTENT);

  const [pageCount, setPageCount] =
    useState(1);

  const [file, setFile] =
    useState<GeneratedFile | null>(null);

  return (
    <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
      <section className="rounded-2xl border bg-white p-6">
        <div className="mb-6">
          <h2 className="text-lg font-semibold">
            PDF Configuration
          </h2>
          <p className="mt-1 text-sm text-neutral-500">
            Configure your dummy PDF.
          </p>
        </div>
        <PdfGeneratorForm file={file} setFile={setFile} setContent={setContent} setPageCount={setPageCount}/>
      </section>
      <section className="rounded-2xl border bg-white p-6">
        <div className="mb-6">
          <h2 className="text-lg font-semibold">
            Generated PDF
          </h2>
          <p className="mt-1 text-sm text-neutral-500">
            Preview your content and download the
            generated PDF.
          </p>
        </div>
        {file ? (
          <div>
            <div className="mb-6 rounded-xl border bg-neutral-50 p-5">
              <div className="grid gap-4 sm:grid-cols-3">
                <div>
                  <p className="text-xs text-neutral-500">
                    Filename
                  </p>

                  <p className="mt-1 truncate text-sm font-medium">
                    {file.filename}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-neutral-500">
                    Size
                  </p>

                  <p className="mt-1 text-sm font-medium">
                    {formatBytes(file.size)}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-neutral-500">
                    Pages
                  </p>

                  <p className="mt-1 text-sm font-medium">
                    {pageCount}
                  </p>
                </div>
              </div>
            </div>
            <div className="mb-6 overflow-hidden rounded-xl border">
              <div className="border-b bg-neutral-50 px-4 py-3 text-xs font-medium text-neutral-500">
                Content Preview
              </div>

              <PdfPreview blob={file.blob}/>
            </div>
            {/* <DownloadButton file={file} /> */}
          </div>
        ) : (
          <div className="flex min-h-80 items-center justify-center rounded-xl border border-dashed">
            <div className="text-center">
              <p className="font-medium">
                No PDF generated
              </p>
              <p className="mt-1 text-sm text-neutral-500">
                Configure your PDF and click Generate
                PDF.
              </p>
            </div>
          </div>
        )}
      </section>
    </div>
  );
}

function formatBytes(bytes: number) {
  if (bytes === 0) {
    return "0 Bytes";
  }

  const units = [
    "Bytes",
    "KB",
    "MB",
    "GB",
  ];

  const index = Math.floor(
    Math.log(bytes) / Math.log(1024)
  );

  return `${(
    bytes / Math.pow(1024, index)
  ).toFixed(2)} ${units[index]}`;
}